IF EXISTS(SELECT NAME FROM SYS.PROCEDURES WHERE NAME = 'PROC_GET_PERQUISITE_VALUE')
BEGIN
DROP PROCEDURE PROC_GET_PERQUISITE_VALUE
END
GO
IF EXISTS(SELECT NAME FROM SYS.PROCEDURES WHERE NAME = 'PROC_CALCULATE_TAX_ON_EXERCISE_NOW')
BEGIN
DROP PROCEDURE PROC_CALCULATE_TAX_ON_EXERCISE_NOW
END
GO

IF EXISTS(SELECT NAME FROM SYS.TYPES WHERE NAME = 'TYPE_PERQ_VALUE')
BEGIN
DROP TYPE TYPE_PERQ_VALUE
END
GO

CREATE TYPE [dbo].[TYPE_PERQ_VALUE] AS TABLE (
    [INSTRUMENT_ID]    BIGINT          NULL,
    [EMPLOYEE_ID]      VARCHAR (50)    NULL,
    [EXERCISE_PRICE]   NUMERIC (18, 9) NULL,
    [OPTION_VESTED]    NUMERIC (18, 9) NULL,
    [FMV_VALUE]        NUMERIC (18, 9) NULL,
    [OPTION_EXERCISED] NUMERIC (18, 9) NULL,
    [GRANTED_OPTIONS]  NUMERIC (18, 9) NULL,
    [EXERCISE_DATE]    DATETIME        NULL,
    [GRANTOPTIONID]    VARCHAR (100)   NULL,
    [GRANTDATE]        VARCHAR (200)   NULL,
    [VESTINGDATE]      VARCHAR (200)   NULL,
    [GRANTLEGSERIALNO] BIGINT          NULL,
    [FROM_DATE]        DATETIME        NULL,
    [TO_DATE]          DATETIME        NULL,
    [TEMP_EXERCISEID]  BIGINT          NULL);
GO

