

If exists (SELECT 'X'
			FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
			WHERE TABLE_NAME='TRANSACTION_COST_METHOD_DETAILS'
			and CONSTRAINT_NAME = 'FK__TRANSACTI__TCMID__4EE89E87'
			)
begin
ALTER TABLE TRANSACTION_COST_METHOD_DETAILS
drop CONSTRAINT FK__TRANSACTI__TCMID__4EE89E87;
end

If Not exists (SELECT 'X'
			FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
			WHERE TABLE_NAME='TRANSACTION_COST_METHOD_DETAILS'
			and CONSTRAINT_type = 'FOREIGN KEY'
			)
begin

ALTER TABLE TRANSACTION_COST_METHOD_DETAILS
ADD  FOREIGN KEY ([TCMID]) REFERENCES [dbo].[TRANSACTION_COST_METHOD_MASTER] ([TCMID]);
end
 
