 

If exists (SELECT 'X'
			FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
			WHERE TABLE_NAME='UserLogHits'
			and CONSTRAINT_NAME = 'FK__UserLogHi__PageI__73A521EA'
			)
begin
ALTER TABLE UserLogHits
drop CONSTRAINT FK__UserLogHi__PageI__73A521EA;
end

If Not exists (SELECT 'X'
			FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
			WHERE TABLE_NAME='UserLogHits'
			and CONSTRAINT_type = 'FOREIGN KEY'
			)
begin

ALTER TABLE UserLogHits
ADD  FOREIGN KEY ([PageID]) REFERENCES [dbo].[PageLogHits] ([PageId]);
end
 