DROP PROCEDURE  IF EXISTS  [dbo].[PROC_CUD_OGA_GRANTVIEWSETTINGS]
GO


SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

If not exists (select 'X' from sys.procedures where name = 'PROC_CUD_OGA_GRANTVIEWSETTINGS')
begin
exec ('
CREATE PROCEDURE [dbo].[PROC_CUD_OGA_GRANTVIEWSETTINGS]
(
	@IS_GRANTDETWITHOUTACCORREJ  BIT = NULL,
	@IS_GRANTDETONLYAFTERACC  BIT = NULL,
	@IS_GRANTDETIFACCORREJ BIT = NULL,
	@IS_GRANTDETDISEXENOWIFNOTACC BIT = NULL,
	@IS_GRANTLETTERBEFOREACC BIT = NULL,
	@IS_GENGRANTLETTERPOSTACC BIT = NULL,
	@UPDATED_BY VARCHAR(50) = NULL,
	@TYPE VARCHAR(30)= NULL,
	@GRANT_VIEW_CONFIG dbo.TypeGrantViewConfiguration  READONLY
)
AS
BEGIN   
	SET NOCOUNT OFF;
	
	IF(@TYPE=''R'')
	BEGIN
			SELECT IS_GRANTDETWITHOUTACCORREJ, IS_GRANTDETONLYAFTERACC, IS_GRANTDETIFACCORREJ, IS_GRANTDETDISEXENOWIFNOTACC,
			IS_GRANTLETTERBEFOREACC, IS_GENGRANTLETTERPOSTACC FROM OGACONDGRANTVIEWSETTINGS

			SELECT LetterAcceptanceStatus, IsViewEnabled, IsDownloadEnabled, CREATED_BY, CREATED_ON, UPDATED_BY, UPDATED_ON
			FROM GrantViewConfiguration
	END
		
	IF(@TYPE=''U'')
	BEGIN	
	
			UPDATE OGACONDGRANTVIEWSETTINGS SET IS_GRANTDETWITHOUTACCORREJ =@IS_GRANTDETWITHOUTACCORREJ, IS_GRANTDETONLYAFTERACC = @IS_GRANTDETONLYAFTERACC, 
												IS_GRANTDETIFACCORREJ = @IS_GRANTDETIFACCORREJ, IS_GRANTDETDISEXENOWIFNOTACC = @IS_GRANTDETDISEXENOWIFNOTACC,
												IS_GRANTLETTERBEFOREACC = @IS_GRANTLETTERBEFOREACC, IS_GENGRANTLETTERPOSTACC = @IS_GENGRANTLETTERPOSTACC,
												UPDATED_BY = @UPDATED_BY, Updated_On = GETDATE()	
			
			         
			        IF NOT EXISTS(SELECT TOP 4 LetterAcceptanceStatus FROM GrantViewConfiguration)
					BEGIN
						--Insert data in Grant View Config table
						INSERT INTO GrantViewConfiguration
						(
							LetterAcceptanceStatus, IsViewEnabled, IsDownloadEnabled, CREATED_BY, CREATED_ON, UPDATED_BY, UPDATED_ON
						)
						SELECT
							LetterAcceptanceStatus, IsViewEnabled, IsDownloadEnabled, @UPDATED_BY, GETDATE(), @UPDATED_BY, GETDATE()
						FROM
							@GRANT_VIEW_CONFIG
					END
					ELSE
					BEGIN
					   
					    --Update Data in grant View Config table
						Update GrantViewConfiguration
						SET LetterAcceptanceStatus = GVC.LetterAcceptanceStatus,
						     IsViewEnabled = GVC.IsViewEnabled,
							 IsDownloadEnabled = GVC.IsDownloadEnabled,
							 UPDATED_BY = @UPDATED_BY,
							 UPDATED_ON = GETDATE()
						FROM 
							@GRANT_VIEW_CONFIG GVC
						Where GrantViewConfiguration.LetterAcceptanceStatus = GVC.LetterAcceptanceStatus
					END
			END
    
END')
end



