sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Tabletype\dbo.CountryandStateType.sql  %Opath%\Error\TableType\dbo.CountryandStateType.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Tabletype\dbo.DelistingInfoType.sql  %Opath%\Error\TableType\dbo.DelistingInfoType.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Tabletype\dbo.EditGrantDetailsMassUploadType.sql  %Opath%\Error\TableType\dbo.EditGrantDetailsMassUploadType.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Tabletype\dbo.ExerciseWindowCloseMassUploadType.sql  %Opath%\Error\TableType\dbo.ExerciseWindowCloseMassUploadType.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Tabletype\dbo.GrntAccMassUpDetType.sql  %Opath%\Error\TableType\dbo.GrntAccMassUpDetType.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Tabletype\dbo.GrpCompDetailType.sql  %Opath%\Error\TableType\dbo.GrpCompDetailType.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Tabletype\dbo.MANAGE_MERCHANTCODE_UPLOAD_TYPE.sql  %Opath%\Error\TableType\dbo.MANAGE_MERCHANTCODE_UPLOAD_TYPE.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Tabletype\dbo.MST_Document_Upload_Master_Details_type.sql  %Opath%\Error\TableType\dbo.MST_Document_Upload_Master_Details_type.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Tabletype\dbo.NAPaymentModeSettingType.sql  %Opath%\Error\TableType\dbo.NAPaymentModeSettingType.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Tabletype\dbo.OGA_TYPE_DYNAMIC_FIELDS.sql  %Opath%\Error\TableType\dbo.OGA_TYPE_DYNAMIC_FIELDS.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Tabletype\dbo.OGA_TYPE_LAST_ACC_DATE_STATUS.sql  %Opath%\Error\TableType\dbo.OGA_TYPE_LAST_ACC_DATE_STATUS.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Tabletype\dbo.PRE_GRANTDATA_DELETION.sql  %Opath%\Error\TableType\dbo.PRE_GRANTDATA_DELETION.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Tabletype\dbo.PUPEXERCISEAPPROVALTYPE.sql  %Opath%\Error\TableType\dbo.PUPEXERCISEAPPROVALTYPE.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Tabletype\dbo.PUPVALIDATEEXERCISE_TYPE.sql  %Opath%\Error\TableType\dbo.PUPVALIDATEEXERCISE_TYPE.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Tabletype\dbo.PUPValueMassUploadType.sql  %Opath%\Error\TableType\dbo.PUPValueMassUploadType.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Tabletype\dbo.SAR_SETTLEMENT_PRICE_MASSUPLOAD.sql  %Opath%\Error\TableType\dbo.SAR_SETTLEMENT_PRICE_MASSUPLOAD.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Tabletype\dbo.SchConcatenationType.sql  %Opath%\Error\TableType\dbo.SchConcatenationType.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Tabletype\dbo.SOPSsUI_EXERCISE_AND_MIT_IDS.sql  %Opath%\Error\TableType\dbo.SOPSsUI_EXERCISE_AND_MIT_IDS.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Tabletype\dbo.SOPSsUI_EXERCISE_EMPLOYEE_IDS.sql  %Opath%\Error\TableType\dbo.SOPSsUI_EXERCISE_EMPLOYEE_IDS.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Tabletype\dbo.SOPSsUI_GET_ALLOTMENT_DATA.sql  %Opath%\Error\TableType\dbo.SOPSsUI_GET_ALLOTMENT_DATA.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Tabletype\dbo.SOPSsUI_GET_BROKER_DETAILS.sql  %Opath%\Error\TableType\dbo.SOPSsUI_GET_BROKER_DETAILS.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Tabletype\dbo.SOPSsUI_GET_DEMAT_DETAILS.sql  %Opath%\Error\TableType\dbo.SOPSsUI_GET_DEMAT_DETAILS.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Tabletype\dbo.SOPSsUI_GET_FVM_DATES.sql  %Opath%\Error\TableType\dbo.SOPSsUI_GET_FVM_DATES.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Tabletype\dbo.SOPSsUI_GET_GRNAT_EXPIRY_DETAILS.sql  %Opath%\Error\TableType\dbo.SOPSsUI_GET_GRNAT_EXPIRY_DETAILS.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Tabletype\dbo.SOPSsUI_GET_MOBILITY_DATA.sql  %Opath%\Error\TableType\dbo.SOPSsUI_GET_MOBILITY_DATA.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Tabletype\dbo.TAXRATESETTING_CONFIG_TYPE.sql  %Opath%\Error\TableType\dbo.TAXRATESETTING_CONFIG_TYPE.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Tabletype\dbo.TRACK_EMP_MOVE_UPLOAD_TYPE.sql  %Opath%\Error\TableType\dbo.TRACK_EMP_MOVE_UPLOAD_TYPE.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Tabletype\dbo.TypeGrantViewConfiguration.sql  %Opath%\Error\TableType\dbo.TypeGrantViewConfiguration.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Tabletype\dbo.TYPE_ALLOTMENT_DATA.sql  %Opath%\Error\TableType\dbo.TYPE_ALLOTMENT_DATA.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Tabletype\dbo.TYPE_AUTOEXERCISE_PAYMENTIDWISE_DETAILS.sql  %Opath%\Error\TableType\dbo.TYPE_AUTOEXERCISE_PAYMENTIDWISE_DETAILS.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Tabletype\dbo.TYPE_CASHPAYOUT_VALUE.sql  %Opath%\Error\TableType\dbo.TYPE_CASHPAYOUT_VALUE.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Tabletype\dbo.TYPE_CRUD_BuyBackOptions.sql  %Opath%\Error\TableType\dbo.TYPE_CRUD_BuyBackOptions.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Tabletype\dbo.TYPE_DELETE_MOBILITY_DATA_TABLE.sql  %Opath%\Error\TableType\dbo.TYPE_DELETE_MOBILITY_DATA_TABLE.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Tabletype\dbo.TYPE_DEMAT_AND_BANKACC_STATUS_MASSUPLOAD.sql  %Opath%\Error\TableType\dbo.TYPE_DEMAT_AND_BANKACC_STATUS_MASSUPLOAD.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Tabletype\dbo.TYPE_DEMAT_DETAILS.sql  %Opath%\Error\TableType\dbo.TYPE_DEMAT_DETAILS.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Tabletype\dbo.TYPE_EMPLOYEE_DATA_ENTITY.sql  %Opath%\Error\TableType\dbo.TYPE_EMPLOYEE_DATA_ENTITY.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Tabletype\dbo.TYPE_EXERCISE_DETAILS.sql  %Opath%\Error\TableType\dbo.TYPE_EXERCISE_DETAILS.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Tabletype\dbo.TYPE_EXERCISE_IDS.sql  %Opath%\Error\TableType\dbo.TYPE_EXERCISE_IDS.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Tabletype\dbo.TYPE_FMV_VALUE.sql  %Opath%\Error\TableType\dbo.TYPE_FMV_VALUE.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Tabletype\dbo.TYPE_FORTENTATIVE_SCHEME.sql  %Opath%\Error\TableType\dbo.TYPE_FORTENTATIVE_SCHEME.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Tabletype\dbo.TYPE_GENERATE_GRANT_LETTER.sql  %Opath%\Error\TableType\dbo.TYPE_GENERATE_GRANT_LETTER.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Tabletype\dbo.TYPE_GET_ENTITY_DATA.sql  %Opath%\Error\TableType\dbo.TYPE_GET_ENTITY_DATA.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Tabletype\dbo.TYPE_GET_EXERCISE_MASSUPLOAD.sql  %Opath%\Error\TableType\dbo.TYPE_GET_EXERCISE_MASSUPLOAD.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Tabletype\dbo.TYPE_GOP_ASSOCIATION.sql  %Opath%\Error\TableType\dbo.TYPE_GOP_ASSOCIATION.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Tabletype\dbo.TYPE_INSERTEXERCISED_TAX.sql  %Opath%\Error\TableType\dbo.TYPE_INSERTEXERCISED_TAX.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Tabletype\dbo.TYPE_INSTRUMENT_DETAILS.sql  %Opath%\Error\TableType\dbo.TYPE_INSTRUMENT_DETAILS.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Tabletype\dbo.TYPE_NOMINEE_DETAILS_APPROVAL.sql  %Opath%\Error\TableType\dbo.TYPE_NOMINEE_DETAILS_APPROVAL.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Tabletype\dbo.TYPE_PERQ_FORAUTOEXERCISE.sql  %Opath%\Error\TableType\dbo.TYPE_PERQ_FORAUTOEXERCISE.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Tabletype\dbo.TYPE_PERQ_TAX_AUTOEXERC.sql  %Opath%\Error\TableType\dbo.TYPE_PERQ_TAX_AUTOEXERC.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Tabletype\dbo.TYPE_PERQ_TAX_VALUE.sql  %Opath%\Error\TableType\dbo.TYPE_PERQ_TAX_VALUE.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Tabletype\dbo.TYPE_PERQ_VALUE.sql  %Opath%\Error\TableType\dbo.TYPE_PERQ_VALUE.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Tabletype\dbo.TYPE_PERQ_VALUE_AUTO_EXE.sql  %Opath%\Error\TableType\dbo.TYPE_PERQ_VALUE_AUTO_EXE.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Tabletype\dbo.TYPE_PROC_TRANSACTION_DETAILS.sql  %Opath%\Error\TableType\dbo.TYPE_PROC_TRANSACTION_DETAILS.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Tabletype\dbo.TYPE_PROP_VALUE.sql  %Opath%\Error\TableType\dbo.TYPE_PROP_VALUE.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Tabletype\dbo.TYPE_PROP_VALUE_AUTO_EXE.sql  %Opath%\Error\TableType\dbo.TYPE_PROP_VALUE_AUTO_EXE.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Tabletype\dbo.TYPE_PYMENTMODE_DETAILS.sql  %Opath%\Error\TableType\dbo.TYPE_PYMENTMODE_DETAILS.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Tabletype\dbo.TYPE_SAR_COMPARATIVE_VALUE.sql  %Opath%\Error\TableType\dbo.TYPE_SAR_COMPARATIVE_VALUE.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Tabletype\dbo.TYPE_SAR_SETTLEMENT_PRICE.sql  %Opath%\Error\TableType\dbo.TYPE_SAR_SETTLEMENT_PRICE.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Tabletype\dbo.TYPE_SAR_STOCK_APPRECIATION.sql  %Opath%\Error\TableType\dbo.TYPE_SAR_STOCK_APPRECIATION.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Tabletype\dbo.TYPE_SAR_TRANSACTION_DATE.sql  %Opath%\Error\TableType\dbo.TYPE_SAR_TRANSACTION_DATE.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Tabletype\dbo.TYPE_SECURITY_ANSWERS.sql  %Opath%\Error\TableType\dbo.TYPE_SECURITY_ANSWERS.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Tabletype\dbo.TYPE_SET_COMPANY_EXCEPTIONS.sql  %Opath%\Error\TableType\dbo.TYPE_SET_COMPANY_EXCEPTIONS.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Tabletype\dbo.TYPE_SET_TAXRATE_EXCEPTIONS.sql  %Opath%\Error\TableType\dbo.TYPE_SET_TAXRATE_EXCEPTIONS.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Tabletype\dbo.TYPE_SHARE_APPR_VALUE.sql  %Opath%\Error\TableType\dbo.TYPE_SHARE_APPR_VALUE.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Tabletype\dbo.TYPE_TAX_RATE_SETTING_MASSUPLOAD.sql  %Opath%\Error\TableType\dbo.TYPE_TAX_RATE_SETTING_MASSUPLOAD.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Tabletype\dbo.TYPE_TEMPLATE_TABLE.sql  %Opath%\Error\TableType\dbo.TYPE_TEMPLATE_TABLE.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Tabletype\dbo.TYPE_WHAT_IF_ANANLYSIS.sql  %Opath%\Error\TableType\dbo.TYPE_WHAT_IF_ANANLYSIS.sql.err
