IF EXISTS(SELECT NAME FROM SYS.PROCEDURES WHERE NAME = 'PROC_GET_FMV_VALUE')
BEGIN
DROP PROCEDURE PROC_GET_FMV_VALUE
END
GO

IF EXISTS(SELECT NAME FROM SYS.TYPES WHERE NAME = 'TYPE_FMV_VALUE')
BEGIN
DROP TYPE TYPE_FMV_VALUE
END
GO

CREATE TYPE [dbo].[TYPE_FMV_VALUE] AS TABLE (
    [INSTRUMENT_ID] BIGINT        NULL,
    [EMPLOYEE_ID]   VARCHAR (50)  NULL,
    [GRANTOPTIONID] VARCHAR (100) NULL,
    [GRANTDATE]     VARCHAR (200) NULL,
    [VESTINGDATE]   VARCHAR (200) NULL,
    [EXERCISE_DATE] DATETIME      NULL,
    [TEMP_TAXFLAG]  VARCHAR (50)  NULL);
GO

