-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
IF EXISTS(SELECT NAME FROM SYS.PROCEDURES WHERE NAME = 'SP_FairValueCalculation')
BEGIN
DROP PROCEDURE SP_FairValueCalculation
END
GO

create    PROCEDURE [dbo].[SP_FairValueCalculation] 
	-- Add the parameters for the stored procedure here
	@DBName VARCHAR(50),
	@LinkedServer VARCHAR(50)
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @USEDB AS VARCHAR (MAX) = 'USE [' + @DBName + ']';
    EXECUTE (@USEDB);
    DECLARE @ClearDataQuery AS VARCHAR (MAX) = 'DELETE FROM [' + @LinkedServer + '].[' + @DBName + '].[dbo].[FairValueCalculation]';
    EXECUTE (@ClearDataQuery);
    IF (OBJECT_ID(N'dbo.ACC_GRANT_REGISTRATION_MASTER', N'U') IS NOT NULL)
        BEGIN
            DECLARE @StrInsertQuery AS VARCHAR (MAX) = 'DELETE FROM [' + @LinkedServer + '].[' + @DBName + '].[dbo].[FairValueCalculation]';
            SET @StrInsertQuery = 'INSERT INTO [' + @LinkedServer + '].[' + @DBName + '].[dbo].[FairValueCalculation]([SCH_SCHEME_ID], [SCH_SCHEME_TITLE], [SCH_OPTION_RATIO_MULTIPLIER], [SCH_OPTION_RATIO_DIVISOR], [GRS_GRANT_REGISTRATION_ID], [GRS_GRANT_DATE],
 [GRS_EXERCISE_PRICE], [GRS_IS_PERFORMANCE_BASED_INCLUDED],	[VPD_VESTING_PERIOD_ID], [VPD_VESTING_DATE], [VPD_EXPIRY_DATE],	[VPD_VESTING_TYPE],
 [VPD_OPTION_TIME_PERCENTAGE], [VPD_OPTION_PERFORMANCE_PERCENTAGE],	[VPD_VESTING_PERIOD_NO], [GOP_GRANT_OPTION_ID],	[GOP_GRANTED_OPTIONS],
 [GOP_EMPLOYEEID], [EMP_EMPLOYEE_NAME],	[GL_ID], [GL_GRANT_LEG_ID],	[GL_SPLIT_QUANTITY], [GL_BONUS_SPLIT_QUANTITY],	[GL_ACC_VESTING_DATE],
 [GL_ACC_EXPIRAY_DATE], [GL_SEPERATION_VESTING_DATE], [GL_SEPERATION_CANCELLATION_DATE], [GL_FINAL_VESTING_DATE], [GL_FINAL_EXPIRAY_DATE],
 [GL_CANCELLATION_DATE], [GL_CANCELLATION_REASON], [GL_CANCELLED_QUANTITY],	[GL_SPLIT_CANCELLED_QUANTITY], [GL_BONUS_SPLIT_CANCELLED_QUANTITY],
 [GL_UNAPPROVED_EXERCISE_QUANTITY],	[GL_EXERCISED_QUANTITY], [GL_SPLIT_EXERCISED_QUANTITY], [GL_BONUS_SPLIT_EXERCISED_QUANTITY], [GL_EXERCISABLE_QUANTITY],
 [GL_UNVESTED_QUANTITY], [GL_LAPSED_QUANTITY], [GL_IS_PERFBASED], [GL_IS_ORIGINAL],	[GL_IS_BONUS], [GL_IS_SPLIT], [SETTLEMENT_OF_OPTIONS],
 [PRICING_FORMULA], [NO_OF_VESTS], [VEST_PERCENT], [TIME_BASED_VEST_PERCENT], [PERFORMANCE_BASED_VEST_PERCENT], [VESTING_FEQUENCY],
 [VESIING_FREQUENCY_VALUE], [VESTING_AFTER_1_YEAR], [EXERCISE_PERIOD], [EXERCISE_PERIOD_FREQ], [EXERCISE_PERIOD_FROM], [MULTIPLE_EXSERCISE_PERIOD],
 [MULT_EXERCISE_PERIOD_VALUE], [TRUST_ROUTE], [RATIO_OPTION], [RATIO_SHARE], [MARKET_PRICE_PER_VEST], [MARKET_PRICE_IV], [EXPECTED_LIFE_PER_VEST],
 [VOLATILITY_PER_VEST],	[RFIR_PER_VEST], [DIVIDEND_PER_VEST], [FAIR_VALUE_PER_VEST], [FV_INCREMENTAL], [INTRINSIC_VALUE_PER_VEST], [IV_INCREMENTAL],
 [DIVIDEND_YIELD_DIVD],	[DIVIDEND_YIELD_MARKET_PRICE], [IS_MRKT_LINKED], [IS_MU_MKT_FV], [IS_MU_MKT_IV])
		(SELECT [SCH_SCHEME_ID], [SCH_SCHEME_TITLE], [SCH_OPTION_RATIO_MULTIPLIER], [SCH_OPTION_RATIO_DIVISOR], [GRS_GRANT_REGISTRATION_ID], [GRS_GRANT_DATE],
 [GRS_EXERCISE_PRICE], [GRS_IS_PERFORMANCE_BASED_INCLUDED],	[VPD_VESTING_PERIOD_ID], [VPD_VESTING_DATE], [VPD_EXPIRY_DATE],	[VPD_VESTING_TYPE],
 [VPD_OPTION_TIME_PERCENTAGE], [VPD_OPTION_PERFORMANCE_PERCENTAGE],	[VPD_VESTING_PERIOD_NO], [GOP_GRANT_OPTION_ID],	[GOP_GRANTED_OPTIONS],
 [GOP_EMPLOYEEID], [EMP_EMPLOYEE_NAME],	[GL_ID], [GL_GRANT_LEG_ID],	[GL_SPLIT_QUANTITY], [GL_BONUS_SPLIT_QUANTITY],	[GL_ACC_VESTING_DATE],
 [GL_ACC_EXPIRAY_DATE], [GL_SEPERATION_VESTING_DATE], [GL_SEPERATION_CANCELLATION_DATE], [GL_FINAL_VESTING_DATE], [GL_FINAL_EXPIRAY_DATE],
 [GL_CANCELLATION_DATE], [GL_CANCELLATION_REASON], [GL_CANCELLED_QUANTITY],	[GL_SPLIT_CANCELLED_QUANTITY], [GL_BONUS_SPLIT_CANCELLED_QUANTITY],
 [GL_UNAPPROVED_EXERCISE_QUANTITY],	[GL_EXERCISED_QUANTITY], [GL_SPLIT_EXERCISED_QUANTITY], [GL_BONUS_SPLIT_EXERCISED_QUANTITY], [GL_EXERCISABLE_QUANTITY],
 [GL_UNVESTED_QUANTITY], [GL_LAPSED_QUANTITY], [GL_IS_PERFBASED], [GL_IS_ORIGINAL],	[GL_IS_BONUS], [GL_IS_SPLIT], [SETTLEMENT_OF_OPTIONS],
 [PRICING_FORMULA], [NO_OF_VESTS], [VEST_PERCENT], [TIME_BASED_VEST_PERCENT], [PERFORMANCE_BASED_VEST_PERCENT], [VESTING_FEQUENCY],
 [VESIING_FREQUENCY_VALUE], [VESTING_AFTER_1_YEAR], [EXERCISE_PERIOD], [EXERCISE_PERIOD_FREQ], [EXERCISE_PERIOD_FROM], [MULTIPLE_EXSERCISE_PERIOD],
 [MULT_EXERCISE_PERIOD_VALUE], [TRUST_ROUTE], [RATIO_OPTION], [RATIO_SHARE], [MARKET_PRICE_PER_VEST], [MARKET_PRICE_IV], [EXPECTED_LIFE_PER_VEST],
 [VOLATILITY_PER_VEST],	[RFIR_PER_VEST], [DIVIDEND_PER_VEST], [FAIR_VALUE_PER_VEST], [FV_INCREMENTAL], [INTRINSIC_VALUE_PER_VEST], [IV_INCREMENTAL],
 [DIVIDEND_YIELD_DIVD],	[DIVIDEND_YIELD_MARKET_PRICE], [IS_MRKT_LINKED], [IS_MU_MKT_FV], [IS_MU_MKT_IV]
		FROM ACC_GRANT_REGISTRATION_DETAILS WITH (NOLOCK))';
            EXECUTE (@StrInsertQuery);
            DECLARE @StrUpdateQuery AS VARCHAR (MAX) = 'Update [' + @LinkedServer + '].[' + @DBName + ']. [dbo].[FairValueCalculation] 
		SET PushDate = ''' + CONVERT (CHAR (50), GetDate(), 121) + '''';
            EXECUTE (@StrUpdateQuery);
        END
END
GO

