sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\View\dbo.VW_Cancellations.sql  -o %Opath%\Error\View\dbo.VW_Cancellations.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\View\dbo.VW_Cancellations_DB.sql  -o %Opath%\Error\View\dbo.VW_Cancellations_DB.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\View\dbo.VW_Cancellation_Year.sql  -o %Opath%\Error\View\dbo.VW_Cancellation_Year.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\View\dbo.VW_Cancellation_Year_DB.sql  -o %Opath%\Error\View\dbo.VW_Cancellation_Year_DB.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\View\dbo.VW_CancelledQuantity.sql  -o %Opath%\Error\View\dbo.VW_CancelledQuantity.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\View\dbo.VW_CancelledQuantity_rpt.sql  -o %Opath%\Error\View\dbo.VW_CancelledQuantity_rpt.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\View\dbo.VW_ExercisedQuantity.sql  -o %Opath%\Error\View\dbo.VW_ExercisedQuantity.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\View\dbo.VW_ExercisedQuantity_rpt.sql  -o %Opath%\Error\View\dbo.VW_ExercisedQuantity_rpt.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\View\dbo.VW_GrantLegDetails.sql  -o %Opath%\Error\View\dbo.VW_GrantLegDetails.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\View\dbo.VW_GRANT_LEG_DETAILS_EXCHANGE_DATA_MYESOP.sql  -o %Opath%\Error\View\dbo.VW_GRANT_LEG_DETAILS_EXCHANGE_DATA_MYESOP.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\View\dbo.VW_GSR.sql  -o %Opath%\Error\View\dbo.VW_GSR.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\View\dbo.VW_GSR_DB.sql  -o %Opath%\Error\View\dbo.VW_GSR_DB.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\View\dbo.VW_Live.sql  -o %Opath%\Error\View\dbo.VW_Live.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\View\dbo.VW_PERQUISITE_TAX_CALCULATION_EXERCISED.sql  -o %Opath%\Error\View\dbo.VW_PERQUISITE_TAX_CALCULATION_EXERCISED.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\View\dbo.VW_PERQUISITE_TAX_CALCULATION_SHEXERCISE.sql  -o %Opath%\Error\View\dbo.VW_PERQUISITE_TAX_CALCULATION_SHEXERCISE.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\View\dbo.VW_PSR.sql  -o %Opath%\Error\View\dbo.VW_PSR.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\View\dbo.VW_PSR_DB.sql  -o %Opath%\Error\View\dbo.VW_PSR_DB.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\View\dbo.VW_RandomUserId.sql  -o %Opath%\Error\View\dbo.VW_RandomUserId.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\View\dbo.VW_REPOSITARY_OF_EXERCISE_DETAILS.sql  -o %Opath%\Error\View\dbo.VW_REPOSITARY_OF_EXERCISE_DETAILS.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\View\dbo.VW_UnApprovedQuantity.sql  -o %Opath%\Error\View\dbo.VW_UnApprovedQuantity.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\View\dbo.VW_UnApprovedQuantity_rpt.sql  -o %Opath%\Error\View\dbo.VW_UnApprovedQuantity_rpt.sql.err
