sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Function\dbo.FN_ACC_EXPLODE_DATES.sql  -o %Opath%\Error\Function\dbo.FN_ACC_EXPLODE_DATES.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Function\dbo.FN_ACC_SPLITSTRING.sql  -o %Opath%\Error\Function\dbo.FN_ACC_SPLITSTRING.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Function\dbo.FN_ConvertAliseToActualField.sql  -o %Opath%\Error\Function\dbo.FN_ConvertAliseToActualField.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Function\dbo.FN_GET_CASHLESSCHARGES.sql  -o %Opath%\Error\Function\dbo.FN_GET_CASHLESSCHARGES.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Function\dbo.FN_GET_CLOSEPRICE.sql  -o %Opath%\Error\Function\dbo.FN_GET_CLOSEPRICE.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Function\dbo.FN_GET_COMPANYMAILSETTINGS.sql  -o %Opath%\Error\Function\dbo.FN_GET_COMPANYMAILSETTINGS.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Function\dbo.FN_GET_COMPANY_DECIMAL_SETTING.sql  -o %Opath%\Error\Function\dbo.FN_GET_COMPANY_DECIMAL_SETTING.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Function\dbo.FN_GET_COM_CODE_VALUE.sql  -o %Opath%\Error\Function\dbo.FN_GET_COM_CODE_VALUE.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Function\dbo.FN_GET_DECIMAL_SETTING_SHARE_VALUE.sql  -o %Opath%\Error\Function\dbo.FN_GET_DECIMAL_SETTING_SHARE_VALUE.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Function\dbo.FN_GET_EMPLOYEE_INSTRUMENT_LIST.sql  -o %Opath%\Error\Function\dbo.FN_GET_EMPLOYEE_INSTRUMENT_LIST.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Function\dbo.FN_GET_EVENTOFINCIDENCE.sql  -o %Opath%\Error\Function\dbo.FN_GET_EVENTOFINCIDENCE.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Function\dbo.FN_GET_EXERCISE_STEP_STATUS.sql  -o %Opath%\Error\Function\dbo.FN_GET_EXERCISE_STEP_STATUS.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Function\dbo.FN_GET_FINAL_FMV.sql  -o %Opath%\Error\Function\dbo.FN_GET_FINAL_FMV.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Function\dbo.FN_GET_FORM_TYPE.sql  -o %Opath%\Error\Function\dbo.FN_GET_FORM_TYPE.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Function\dbo.FN_GET_LINK_BY_CONTROL_MASTER_ID.sql  -o %Opath%\Error\Function\dbo.FN_GET_LINK_BY_CONTROL_MASTER_ID.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Function\dbo.FN_GET_QUANTITYWithSCHEME.sql  -o %Opath%\Error\Function\dbo.FN_GET_QUANTITYWithSCHEME.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Function\dbo.FN_GET_STATES_BY_COUNTRY.sql  -o %Opath%\Error\Function\dbo.FN_GET_STATES_BY_COUNTRY.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Function\dbo.FN_GET_TENTATIVE_TAX.sql  -o %Opath%\Error\Function\dbo.FN_GET_TENTATIVE_TAX.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Function\dbo.FN_IS_SAR_COVER.sql  -o %Opath%\Error\Function\dbo.FN_IS_SAR_COVER.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Function\dbo.fn_MVParam.sql  -o %Opath%\Error\Function\dbo.fn_MVParam.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Function\dbo.FN_PQ_TAX_ROUNDING.sql  -o %Opath%\Error\Function\dbo.FN_PQ_TAX_ROUNDING.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Function\dbo.FN_ROUND_VALUE.sql  -o %Opath%\Error\Function\dbo.FN_ROUND_VALUE.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Function\dbo.FN_SPLIT_STRING.sql  -o %Opath%\Error\Function\dbo.FN_SPLIT_STRING.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Function\dbo.FN_VALIDATE_EMAIL_ID.sql  -o %Opath%\Error\Function\dbo.FN_VALIDATE_EMAIL_ID.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Function\dbo.FUNC_GET_PERQ_VALUE_PAYABLE.sql  -o %Opath%\Error\Function\dbo.FUNC_GET_PERQ_VALUE_PAYABLE.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Function\dbo.FUNC_GET_SAR_PERQ_VAL_PAYABLE.sql  -o %Opath%\Error\Function\dbo.FUNC_GET_SAR_PERQ_VAL_PAYABLE.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Function\dbo.FUNC_GET_SHARE_ISSUE_SAR.sql  -o %Opath%\Error\Function\dbo.FUNC_GET_SHARE_ISSUE_SAR.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Function\dbo.FUNC_GET_SHARE_PRICE.sql  -o %Opath%\Error\Function\dbo.FUNC_GET_SHARE_PRICE.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Function\dbo.FUNC_GET_SHARE_PRICE_FOR_SAR.sql  -o %Opath%\Error\Function\dbo.FUNC_GET_SHARE_PRICE_FOR_SAR.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Function\dbo.FUNC_GET_VESTINGTYPE.sql  -o %Opath%\Error\Function\dbo.FUNC_GET_VESTINGTYPE.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Function\dbo.FunEmployeeDematDetails.sql  -o %Opath%\Error\Function\dbo.FunEmployeeDematDetails.sql.err
sqlcmd -S %SName% -U %UName% -P %Pwd% -d %DbName% -I -i %Opath%\Function\dbo.udf_hits.sql  -o %Opath%\Error\Function\dbo.udf_hits.sql.err
