

If exists (SELECT 'X'
			FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
			WHERE TABLE_NAME='MASTER_LIST_FLD_VALUE'
			and CONSTRAINT_NAME = 'FK__MASTER_LI__MLFN___66F53242'
			)
begin
ALTER TABLE MASTER_LIST_FLD_VALUE
drop CONSTRAINT FK__MASTER_LI__MLFN___66F53242;
end

If Not exists (SELECT 'X'
			FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
			WHERE TABLE_NAME='MASTER_LIST_FLD_VALUE'
			and CONSTRAINT_type = 'FOREIGN KEY'
			)
begin

ALTER TABLE MASTER_LIST_FLD_VALUE
ADD  FOREIGN KEY ([MLFN_ID])
    REFERENCES [dbo].[MASTER_LIST_FLD_NAME] ([MLFN_ID]);
end
 