
If exists ( SELECT *
			FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
			WHERE TABLE_NAME='BROKER_SETTINGS'
			and CONSTRAINT_NAME = 'FK__BROKER_SE__EMPLO__7C5A637C'
			)
begin
ALTER TABLE BROKER_SETTINGS
drop CONSTRAINT FK__BROKER_SE__EMPLO__7C5A637C;
end


If Not exists (SELECT 'X'
			FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
			WHERE TABLE_NAME='BROKER_SETTINGS'
			and CONSTRAINT_type = 'FOREIGN KEY'
			)
begin

ALTER TABLE BROKER_SETTINGS
ADD   FOREIGN KEY ([EMPLOYEEID]) REFERENCES [dbo].[EmployeeMaster] ([EmployeeID])

end