
If exists ( SELECT *
			FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
			WHERE TABLE_NAME='AUDITTRAILOFSCHEME'
			and CONSTRAINT_NAME = 'FK__AUDITTRAI__Schem__45DE573A'
			)
begin
ALTER TABLE AUDITTRAILOFSCHEME
CHECK CONSTRAINT FK__AUDITTRAI__Schem__45DE573A;
end

/*
ALTER TABLE Orders
ADD FOREIGN KEY (PersonID) REFERENCES Persons(PersonID);
*/