

If exists (SELECT 'X'
			FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
			WHERE TABLE_NAME='HRMSMappingsValues'
			and CONSTRAINT_NAME = 'FK__HRMSMappi__HRMSM__76177A41'
			)
begin
ALTER TABLE HRMSMappingsValues
drop CONSTRAINT FK__HRMSMappi__HRMSM__76177A41;
end

If Not exists (SELECT 'X'
			FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
			WHERE TABLE_NAME='HRMSMappingsValues'
			and CONSTRAINT_type = 'FOREIGN KEY'
			)
begin

ALTER TABLE HRMSMappingsValues
ADD  FOREIGN KEY (HRMSMappingsFldID)
    REFERENCES [dbo].[HRMSMappingsFields] ([HRMSMappingsFldID]);
end